### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by giacomoalonzi** [sharadcodes/covid19-graphql#1]
Hello, I found inconsistent data for Italian numbers. I'm using your data [here](https://covidlive.it/en) but as you can see there is an inconsistency with my new daily positive and yours. Do you know why? Where do you get Italian data?

Thanks for the amazing job!

**Comment by sharadcodes** [comment]
> Hello, I found inconsistent data for Italian numbers. I'm using your data [here](https://covidlive.it/en) but as you can see there is an inconsistency with my new daily positive and yours. Do you know why? Where do you get Italian data?
> 
> Thanks for the amazing job!

How much is the difference ? @giacomoalonzi

**Comment by giacomoalonzi** [comment]
Let me explain better:

As you can see on [this](https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json) file (my source) the `nuovi_attualmente_positivi` value is different than your `todayCases` value.

**Comment by sharadcodes** [comment]
> Let me explain better:
> 
> As you can see on [this](https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json) file (my source) the `nuovi_attualmente_positivi` value is different than your `todayCases` value.

Let me see

**Comment by sharadcodes** [comment]
There is no problem in my data... I think its with your another api or cache stuff.
