### ISSUE TITLE
Expected Iterable, but did not find one for field Covid19.countries.

### ISSUE THREAD

**Issue by giacomoalonzi** [sharadcodes/covid19-graphql#2]
"Expected Iterable, but did not find one for field Covid19.countries.

**Comment by sharadcodes** [comment]
Can you please show the code you used I can't say anything without code.

**Comment by giacomoalonzi** [comment]
Hello @sharadcodes, I found this error yesterday. It happened also on your graphql demo page with your demo code. 
Thanks

**Comment by sharadcodes** [comment]
Now is it there or not ?
