### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by giacomoalonzi** [sharadcodes/covid19-graphql#3]
Hello, how do you sort data? USA today has more cases than Cina but Cina is still on top. 

Thanks!

**Comment by sharadcodes** [comment]
> Hello, how do you sort data? USA today has more cases than Cina but Cina is still on top.
> 
> Thanks!

I've not implemented sorting and all only fetching of data is possible. I'll add it in an hour

**Comment by giacomoalonzi** [comment]
wow, that's awesome @sharadcodes  ⚡️ Thanks

**Comment by sharadcodes** [comment]
> wow, that's awesome @sharadcodes  Thanks

It'll take some time Quite busy

**Comment by sharadcodes** [comment]
> wow, that's awesome @sharadcodes  Thanks

It has been added. Take a look at README
