### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by giacomoalonzi** [sharadcodes/covid19-graphql#4]
Access to XMLHttpRequest at 'https://sharad-gql-covid19.herokuapp.com/graphql' from origin 'https://www.covidlive.it' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sharadcodes** [comment]
Let me see

**Comment by sharadcodes** [comment]
Fixed now

**Comment by giacomoalonzi** [comment]
Thank you Sir 😇
